### ISSUE TITLE
Nonetype error occuring in second image

### ISSUE THREAD

**Issue by Formanj-0** [MunskyGroup/FISH_Processing#2]
![Screenshot from 2024-06-19 13-51-37](https://github.com/MunskyGroup/FISH_Processing/assets/155103214/44ed0333-b51c-41cf-a2d4-1f79ae628037)
When running the FISH pipeline I am running into a nonetype error during the second image in the series of processing

**Comment by gagayuan** [comment]
**I encountered the exact same problem，how to solve ？ @luisub @voduchuy @alexpopinga @Formanj-0** 

**I am experiencing the following error when testing cluster/runner_local.sh:**


`Image shape:  (27, 928, 624, 4) 

Number of images:  2 

Local directory with images:  /data/fishProcess/FISH_Processing/xuxi_test/images/MS2-CY5_Cyto543_560_woStim_xuxiSmall2 


 Output folder name :  MS2-CY5_Cyto543_560_woStim_xuxiSmall2___nuc_125__cyto_225__psfz_500__psfyx_160__ts_None

 ###################### 
        IMAGE : 0
 ###################### 
    Image Name :   ROI001_XY1657814108_Z00_T0_merged.tif
    Orginal Image Shape :                     [27, 928, 624, 4]
    Trimmed z_slices at each border :         1
    Image sharpness metric :                  1.189

 ###################### 
        IMAGE : 1
 ###################### 
    Image Name :   ROI002_XY1657815441_Z00_T0_merged.tif
    Orginal Image Shape :                     [27, 928, 624, 4]
    Trimmed z_slices at each border :         1
    Image sharpness metric :                  1.193
Traceback (most recent call last):
  File "/data/fishProcess/FISH_Processing/src/pipeline_executable.py", line 169, in <module>
    save_pdf_report=save_pdf_report).run()
  File "/data/fishProcess/FISH_Processing/src/fish_analyses.py", line 2732, in run
    Plots().plot_all_cells_and_spots(list_images=self.list_images, 
  File "/data/fishProcess/FISH_Processing/src/fish_analyses.py", line 5265, in plot_all_cells_and_spots
    number_cells = np.max(complete_dataframe['cell_id'].values)+1
TypeError: 'NoneType' object is not subscriptable`



**My parameters are as follows:**

NUMBER_OF_CORES=2
diameter_nucleus=125
diameter_cytosol=225
psf_z=500
psf_yx=160
voxel_size_z=500
voxel_size_yx=160
channels_with_nucleus='[0]'
channels_with_cytosol='[2]'
channels_with_FISH='[3]'
send_data_to_NAS=0
download_data_from_NAS=0
path_to_masks_dir='None'
save_all_images=0
threshold_for_spot_detection='None'
save_filtered_images=0
optimization_segmentation_method='default'
remove_z_slices_borders=1
remove_out_of_focus_images=1
save_pdf_report=0
convert_to_standard_format=0
number_color_channels=0
number_of_fov=0
use_metadata=0
is_format_FOV_Z_Y_X_C=0


**It may be that the dataframe located in src/fish_analyses.py at line 2731 is empty and I don't quite understand why.
The test tiff image I used is from MS2-CY5_Cyto543_560_woStim.zip from https://zenodo.org/records/7868322
Is it possible that I'm not using the correct input image?**
